services:
  - type: web
    name: diario-classe-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
