-- ============================================================
-- SQL INSERT - Servidores EMEIEF Luiz Gonzaga - Maio 2026
-- Total: 90 servidores extraídos do PDF de frequência
-- Gerado automaticamente a partir de: 68366520-maio.pdf
-- ============================================================

-- PASSO 1: Criar tabela Servidor
CREATE TABLE IF NOT EXISTS public."Servidor" (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    rf VARCHAR(20) NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    cargo TEXT,
    periodo TEXT CHECK (periodo IN ('Manha', 'Tarde', 'Noite')),
    escola TEXT DEFAULT 'EMEIEF LUIZ GONZAGA',
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- PASSO 2: Permissões (compatível com o padrão do DiárioClasse)
GRANT ALL ON public."Servidor" TO anon;
GRANT ALL ON public."Servidor" TO authenticated;
ALTER TABLE public."Servidor" DISABLE ROW LEVEL SECURITY;
NOTIFY pgrst, 'reload schema';

-- PASSO 3: Inserir os 90 servidores
INSERT INTO public."Servidor" (rf, nome, cargo, periodo) VALUES
  ('357200', 'ADRIANA DE OLIVEIRA CAETANO DANTAS', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('595608', 'ADRIANA ZENOBES DA SILVA OLIVEIRA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('554472', 'ALESSANDRA NEVES DE OLIVEIRA FERREIRA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('620335', 'ALINE ALVES GADOTI', 'PROFESSOR DE EDUCACAO FUNDAMENTAL II - ARTES', 'Tarde'),
  ('614513', 'ALINE APARECIDA SIQUEIRA RODRIGUES', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('534277', 'ALINE DE FARIA DIVINO', 'PROF ASSESSOR DE EDUC INCLUSIV', 'Manha'),
  ('618748', 'ANA CLAUDIA CORREIA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('612340', 'ANDRE PEZZOTTI', 'PROF EDUC FUND II - ARTES', 'Manha'),
  ('589780', 'ANDRESSA SOUZA DA SILVA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('417467', 'ANGELITA SILVA MENEZES', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('406686', 'APARECIDA MARIA DRIGO DA SILVA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('1313517', 'BEATRIZ ALEXSANDRA PEREIRA DE SOUZA', 'ESTAGIARIO DE PEDAGOGIA', 'Manha'),
  ('594415', 'BIANCA CORADINO DE PAULA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('590231', 'BRUNA DE SOUZA PICELI', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('612260', 'BRUNA LUIZA DE CARVALHO RUIZ', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('1311093', 'BRUNA SANTANA DA PAZ', 'ESTAGIARIO DE PEDAGOGIA', 'Manha'),
  ('588962', 'BRUNO CRISTINO', 'PROFESSOR DE EDUCACAO FISICA', 'Manha'),
  ('618845', 'CAMILA BEATRIZ DE ARAUJO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('494925', 'CAMILA PANDOLFO', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('613371', 'CAROLINE ALVES DE OLIVEIRA FERREIRA', 'PROFESSOR DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO', 'Manha'),
  ('594490', 'CATIA JUSTINO DA SILVA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('303640', 'CATIA SILVA DOS SANTOS FERNANDES MIGUEL', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('493643', 'CELINA CARVALHO GALDINO DA SILVA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('500259', 'CESAR JOSE DA SILVEIRA', 'PROFESSOR DE EDUCACAO FISICA', 'Manha'),
  ('543284', 'CINTHIA FERREIRA DA SILVA', 'ASSISTENTE PEDAGOGICO', 'Manha'),
  ('579955', 'CLEUSA MARTINS DIAS', 'AGENTE DE INCLUSAO ESCOLAR', 'Manha'),
  ('620874', 'CRISTINA SANTOS MOREIRA', 'PROFESSOR DE EDUCACAO FUNDAMENTAL II - ARTES', 'Tarde'),
  ('429074', 'DANIELLE APARECIDA PAGANO LOPES', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('357618', 'DENISE MONTEIRO DA COSTA LOFEU', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('1312324', 'EDUARDO QUIEROTI RODRIGUES', 'PROFESSOR DE EDUCACAO FISICA', 'Manha'),
  ('261360', 'ELAINE APARECIDA DA SILVA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Noite'),
  ('594733', 'ELIANE FERNANDES CANDIDO DA SILVA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('553735', 'ELIAS DE LIMA NOVAES', 'SERVENTE GERAL', 'Manha'),
  ('343501', 'EMERSON ANDREI DE MELLO', 'ASSISTENTE PEDAGOGICO', 'Manha'),
  ('1300164', 'ERICA SOUZA DOS SANTOS', 'ESTAGIARIO DE PEDAGOGIA', 'Tarde'),
  ('582000', 'FABIANA SETE YUPANQUI', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('543616', 'FERNANDA DE SOUZA SILVA GOIVINHO', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('954080', 'FERNANDA FERREIRA PEREIRA', 'ESTAGIARIO DE PEDAGOGIA', 'Tarde'),
  ('580260', 'FERNANDA SILVA SOUZA', 'AGENTE DE INCLUSAO ESCOLAR', 'Manha'),
  ('594814', 'FERNANDA SOUZA TAVARES DA PIEDADE', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('303879', 'GILMARA JANUARIO IBELLI', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('1301268', 'HELENA MARIA DA SILVA ALVES', 'MERENDEIRA', 'Manha'),
  ('563714', 'HELLEN PAMELA DA SILVA BATISTA', 'MERENDEIRA', 'Manha'),
  ('552224', 'IONE PEREIRA DE ANDRADE RIBEIRO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('952478', 'JAQUELINE PENGUE FERNANDES', 'ESTAGIARIO DE PEDAGOGIA', 'Manha'),
  ('558567', 'JESSICA DE PAULA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('537438', 'JOSE RICARDO DE OLIVEIRA', 'ASSISTENTE II', 'Manha'),
  ('585254', 'JULIA DE LIMA MARTINELLI', 'MERENDEIRA', 'Manha'),
  ('611948', 'JULIANA APARECIDA DE ARAUJO LUIZ', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('556769', 'KAMILA PIRES DE SOUZA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('583359', 'KARINE ARAUJO LIMA DE JESUS', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('620483', 'KIMBERLY FRANULOVIC', 'PROFESSOR DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO', 'Manha'),
  ('580732', 'LILIANE DE SOUZA SANTOS SAKAI', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('262552', 'LUCIANY ROMEIRA DE MORAES DUARTE', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('591777', 'MAGNUS GIANCARLO PEREIRA CAMPOS', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('539023', 'MARIA DOS ANJOS FERREIRA DO CARMO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Noite'),
  ('391816', 'MARIA FRANCISCA DO NASCIMENTO RODRIGUES', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('377783', 'MARIA LUCIA MENDONCA ROCHA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('316474', 'MARTHA CONCEICAO DA SILVA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('357510', 'MICHELE VILCINSKI DA SILVA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('1301896', 'MICHELLE GERMANO DO NASCIMENTO', 'PROFESSOR DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO', 'Manha'),
  ('614785', 'NAILDO DONIZETE VIEIRA', 'AUXILIAR ADMINISTRATIVO', 'Manha'),
  ('496782', 'PAULA ANDREIA DA SILVA REIS', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('322814', 'PRISCILA SILVA SALTAO LYRIO', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('513512', 'RAFAEL SILVA GUIMARAES', 'MONITOR DE INCLUSAO DIGITAL', 'Manha'),
  ('402680', 'RAQUEL LINARES FERREIRA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('569330', 'ROSANA RODRIGUES DOS SANTOS', 'PROF EDU INF E ENS FUNDAMENTAL', 'Tarde'),
  ('572136', 'ROSANGELA MARTINES SORIA MOREIRA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('590037', 'ROSANGELA MOREIRA ARAUJO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('357812', 'ROSELI MARIA DE AZEVEDO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('225355', 'ROSELI ZAMANA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('583766', 'SABRINA MARIA MACARIO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('1310445', 'SABRINA MARIA MACARIO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('303623', 'SANDRA DOS SANTOS', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('592099', 'SANDRA DOS SANTOS TARGA AQUINO', 'SERVENTE GERAL', 'Manha'),
  ('559326', 'SERGIO LUIS FERREIRA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('578940', 'SILENE DE CARVALHO DA SILVA', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde'),
  ('261424', 'SILVANA APARECIDA ROCHA BEZERRA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('514497', 'SILVIO CESAR REVUELTA TAVARES', 'VICE-DIRETOR DE UNID ESCOLAR', 'Manha'),
  ('359734', 'SOLANGE APARECIDA GAVIOLI ISQUINGI', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('569500', 'SONIA APARECIDA VIANA GARCIA', 'PROF EDU INF E ENS FUNDAMENTAL', 'Noite'),
  ('950190', 'STEFANY GOMES DA SILVA', 'ESTAGIARIO DE PEDAGOGIA', 'Noite'),
  ('486337', 'STEPHANIE PINHEIRO CARDOSO', 'PROFESSOR DE EDUCACAO FISICA', 'Tarde'),
  ('596680', 'SUZANA GUERRA CHELEGAO', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Manha'),
  ('493457', 'TANIA DE GOIS SOUZA VIEIRA', 'ASSISTENTE PEDAGOGICO', 'Manha'),
  ('205036', 'TEREZINHA BABICHAKA SQUIAVONI', 'DIRETOR DE UNIDADE ESCOLAR', 'Manha'),
  ('323039', 'THABATA DE CARVALHO VIAJANTE', 'PROF EDU INF E ENS FUNDAMENTAL', 'Manha'),
  ('595225', 'VALERIA COUTO DA SILVA', 'PROFESSOR DE EDUCACAO FISICA', 'Manha'),
  ('486752', 'VANIUZA APARECIDA MESSIAS', 'MERENDEIRA', 'Manha'),
  ('1310283', 'VERONICA APARECIDA DOS SANTOS', 'PROFESSOR DE EDUCACAO INFANTIL E ENSINO FUNDAMENTAL', 'Tarde')
ON CONFLICT (rf) DO UPDATE SET
  nome = EXCLUDED.nome,
  cargo = EXCLUDED.cargo,
  periodo = EXCLUDED.periodo,
  updated_at = NOW();

-- PASSO 4: Verificar resultado
SELECT 
  periodo,
  COUNT(*) AS total,
  STRING_AGG(cargo, ', ' ORDER BY cargo) FILTER (WHERE cargo IS NOT NULL) AS cargos
FROM public."Servidor"
GROUP BY periodo
ORDER BY periodo;

SELECT COUNT(*) AS total_servidores FROM public."Servidor";
