-- RODAR NO SUPABASE SQL EDITOR antes de usar o app

ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS ra BIGINT;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS dig_ra TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_nascimento TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_inicio_matricula TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_fim_matricula TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_movimentacao TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS deficiencia TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS bolsa_familia BOOLEAN DEFAULT FALSE;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS situacao TEXT DEFAULT 'ATIVO';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS professora TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS numero INTEGER DEFAULT 0;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS nis TEXT DEFAULT NULL;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS responsavel TEXT DEFAULT NULL;

ALTER TABLE "Turma" ADD COLUMN IF NOT EXISTS professora TEXT DEFAULT '';

ALTER TABLE "Falta" ADD COLUMN IF NOT EXISTS frequencia_texto TEXT DEFAULT '';
