-- RODAR NO SUPABASE SQL EDITOR antes de usar o app

ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS ra BIGINT;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS dig_ra TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_nascimento TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_inicio_matricula TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_fim_matricula TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS data_movimentacao TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS deficiencia TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS bolsa_familia BOOLEAN DEFAULT FALSE;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS situacao TEXT DEFAULT 'ATIVO';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS professora TEXT DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS numero INTEGER DEFAULT 0;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS nis TEXT DEFAULT NULL;
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS responsavel TEXT DEFAULT NULL;

ALTER TABLE "Turma" ADD COLUMN IF NOT EXISTS professora TEXT DEFAULT '';

ALTER TABLE "Falta" ADD COLUMN IF NOT EXISTS frequencia_texto TEXT DEFAULT '';

-- Tabela para submissões dos professores aguardando revisão
CREATE TABLE IF NOT EXISTS "Pendente" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  turmaId UUID REFERENCES "Turma"(id) ON DELETE CASCADE,
  mes INTEGER NOT NULL,
  ano INTEGER NOT NULL DEFAULT 2026,
  status TEXT DEFAULT 'pendente',  -- pendente | aprovado | rejeitado
  dados JSONB NOT NULL DEFAULT '[]',
  total_entradas INTEGER DEFAULT 0,
  total_problemas INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE "Pendente" DISABLE ROW LEVEL SECURITY;
