import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../api';
import { btn, theme } from '../styles';

const TOKEN_KEY='censo_direto_token';
type Campo={key:string;label:string;section:string;type:string};
type Convite={id:string;status:string;campos?:Campo[];respostas?:Record<string,any>;criado_em?:string;expira_em?:string;respondido_em?:string;conferido_em?:string};
type Professor={rf:string;rfExibicao:string;nome:string;turma:string;periodo:string;camposPendentes:number;campos:string[];convite?:Convite|null};
type Detalhe={id:string;ano:number;rf:string;nome:string;turma:string;periodo:string;status:string;campos:Campo[];respostas:Record<string,any>;respondido_em?:string};

const txt=(v:unknown)=>String(v??'').trim();
function formatRf(rf:string){const d=rf.replace(/\D/g,'');return d.length===6?`${d.slice(0,2)}.${d.slice(2,5)}-${d.slice(5)}`:rf}
function formatDataHora(v?:string){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function valor(v:any){if(v===true)return'Sim';if(v===false)return'Não';return txt(v)||'—'}

export default function CensoProfessorConvites(){
  const[token,setToken]=useState(()=>sessionStorage.getItem(TOKEN_KEY)||'');
  const[professores,setProfessores]=useState<Professor[]>([]),[loading,setLoading]=useState(false),[erro,setErro]=useState(''),[aviso,setAviso]=useState(''),[competencia,setCompetencia]=useState<{ano:number;mes:number}|null>(null);
  const[links,setLinks]=useState<Record<string,string>>({}),[gerando,setGerando]=useState(''),[detalhe,setDetalhe]=useState<Detalhe|null>(null),[conferindo,setConferindo]=useState(false);

  useEffect(()=>{const id=window.setInterval(()=>{const atual=sessionStorage.getItem(TOKEN_KEY)||'';setToken(t=>t===atual?t:atual)},600);return()=>window.clearInterval(id)},[]);

  const invoke=async(body:Record<string,any>)=>{
    const headers:Record<string,string>={};if(token)headers['x-censo-token']=token;
    const{data,error}=await supabase.functions.invoke('censo-professor-formulario',{body,headers});
    if(error){let msg=error.message||'Falha na coleta com professores.';const ctx=(error as any).context;try{if(ctx&&typeof ctx.json==='function'){const detail=await ctx.json();if(detail?.erro)msg=detail.erro}}catch{}throw new Error(msg)}
    if(!data?.ok)throw new Error(data?.erro||'Operação não autorizada.');return data;
  };
  const carregar=async()=>{if(!token){setProfessores([]);setCompetencia(null);return}setLoading(true);setErro('');try{const r=await invoke({action:'admin-list'});setProfessores(Array.isArray(r.professores)?r.professores:[]);setCompetencia(r.competencia||null)}catch(e:any){setErro(e?.message||'Não foi possível carregar a coleta com professores.')}finally{setLoading(false)}};
  useEffect(()=>{void carregar()},[token]);

  const gerar=async(p:Professor)=>{setGerando(p.rf);setErro('');setAviso('');try{const r=await invoke({action:'admin-generate',rf:p.rf});setLinks(x=>({...x,[p.rf]:r.link}));setAviso(`Link individual gerado para ${p.nome}.`);await carregar()}catch(e:any){setErro(e?.message||'Não foi possível gerar o link.')}finally{setGerando('')}};
  const copiar=async(p:Professor)=>{const link=links[p.rf];if(!link)return;try{await navigator.clipboard.writeText(link);setAviso(`Link de ${p.nome} copiado. Agora você pode enviar pelo WhatsApp.`)}catch{setAviso(`Copie este link: ${link}`)}};
  const abrirDetalhe=async(id:string)=>{setErro('');try{const r=await invoke({action:'admin-detail',id});setDetalhe(r.convite)}catch(e:any){setErro(e?.message||'Não foi possível abrir a resposta.')}};
  const confirmar=async()=>{if(!detalhe)return;setConferindo(true);setErro('');try{const r=await invoke({action:'admin-confirm',id:detalhe.id});setAviso(r.mensagem||'Dados conferidos e incorporados ao Banco Mestre.');setDetalhe(null);await carregar()}catch(e:any){setErro(e?.message||'Não foi possível confirmar a resposta.')}finally{setConferindo(false)}};

  const aguardando=useMemo(()=>professores.filter(p=>p.convite?.status==='respondido').length,[professores]);
  if(!token)return null;

  return<section style={{background:theme.card,border:`1px solid ${aguardando?theme.warning:theme.border}`,borderRadius:theme.radiusMd,boxShadow:theme.shadow,padding:16,marginBottom:14}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div style={{color:theme.text,fontWeight:950,fontSize:15}}>📨 Coleta individual com professores</div><div style={{color:theme.textSecondary,fontSize:11.5,marginTop:4,lineHeight:1.5}}>Cruzamento automático: <strong>A preparar ∩ turmas regulares</strong>. O link mostra somente os campos que ainda faltam. A resposta só entra no Banco Mestre depois da sua conferência.</div>{competencia&&<div style={{color:theme.textMuted,fontSize:10.5,marginTop:4}}>Competência: {String(competencia.mes).padStart(2,'0')}/{competencia.ano}</div>}</div><div style={{display:'flex',gap:7,alignItems:'center'}}>{aguardando>0&&<span style={{padding:'6px 9px',borderRadius:999,background:`${theme.warning}18`,color:theme.warning,fontSize:10.5,fontWeight:900}}>⚠️ {aguardando} aguardando sua conferência</span>}<button style={btn('ghost',{small:true})} disabled={loading} onClick={()=>void carregar()}>{loading?'Atualizando...':'Atualizar'}</button></div></div>
    {aviso&&<div style={{marginTop:10,padding:9,borderRadius:8,background:`${theme.success}0F`,border:`1px solid ${theme.success}44`,color:theme.textSecondary,fontSize:11.5}}>{aviso}</div>}
    {erro&&<div style={{marginTop:10,padding:9,borderRadius:8,background:`${theme.danger}0F`,border:`1px solid ${theme.danger}44`,color:theme.danger,fontSize:11.5,fontWeight:800}}>{erro}</div>}
    <div style={{overflowX:'auto',marginTop:12}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:880}}><thead><tr style={{background:'var(--ghost-bg)'}}>{['Professor','RF','Turma','Pendências','Situação da coleta','Ação'].map(h=><th key={h} style={{padding:'9px 8px',textAlign:'left',fontSize:10.5,color:theme.textSecondary,borderBottom:`1px solid ${theme.border}`}}>{h}</th>)}</tr></thead><tbody>{professores.length===0?<tr><td colSpan={6} style={{padding:14,color:theme.textMuted,fontSize:11.5}}>{loading?'Carregando…':'Nenhum professor regente pendente precisa de coleta neste momento.'}</td></tr>:professores.map(p=>{const c=p.convite||null;const status=c?.status||'sem_link';const cor=status==='respondido'?theme.warning:status==='conferido'?theme.success:status==='aberto'?theme.primaryText:theme.textMuted;return<tr key={p.rf} style={{borderBottom:`1px solid ${theme.border}`}}><td style={{padding:'10px 8px',color:theme.text,fontSize:12,fontWeight:850}}>{p.nome}</td><td style={{padding:'10px 8px',color:theme.textSecondary,fontSize:11}}>{formatRf(p.rfExibicao||p.rf)}</td><td style={{padding:'10px 8px',color:theme.textSecondary,fontSize:11}}>{p.turma}{p.periodo?` · ${p.periodo}`:''}</td><td style={{padding:'10px 8px',color:p.camposPendentes?theme.warning:theme.success,fontSize:11,fontWeight:800}}>{p.camposPendentes?`${p.camposPendentes} campo(s)`:'✓ dados completos'}</td><td style={{padding:'10px 8px',color:cor,fontSize:10.5,fontWeight:900}}>{status==='respondido'?`🟡 RESPONDIDO · ${formatDataHora(c?.respondido_em)}`:status==='conferido'?`✅ CONFERIDO · ${formatDataHora(c?.conferido_em)}`:status==='aberto'?`🔗 LINK GERADO · válido até ${formatDataHora(c?.expira_em)}`:'⚪ LINK AINDA NÃO GERADO'}</td><td style={{padding:'10px 8px'}}><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{status==='respondido'&&c?.id?<button style={btn('primary',{small:true})} onClick={()=>void abrirDetalhe(c.id)}>Conferir resposta</button>:status==='conferido'?<span style={{color:theme.success,fontSize:10.5,fontWeight:850}}>Agora use “Preparar formulário” abaixo.</span>:p.camposPendentes>0&&<button style={btn('ghost',{small:true})} disabled={gerando===p.rf} onClick={()=>void gerar(p)}>{gerando===p.rf?'Gerando...':status==='aberto'?'Gerar novo link':'Gerar link'}</button>}{links[p.rf]&&<button style={btn('success',{small:true})} onClick={()=>void copiar(p)}>📋 Copiar link</button>}</div></td></tr>})}</tbody></table></div>

    {detalhe&&<div style={{marginTop:14,border:`2px solid ${theme.warning}66`,borderRadius:10,padding:14,background:'var(--ghost-bg)'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><div style={{fontSize:14,fontWeight:950,color:theme.text}}>Conferir resposta — {detalhe.nome}</div><div style={{fontSize:10.5,color:theme.textMuted,marginTop:3}}>RF {formatRf(detalhe.rf)} · {detalhe.turma} · respondido em {formatDataHora(detalhe.respondido_em)}</div></div><button style={btn('ghost',{small:true})} onClick={()=>setDetalhe(null)}>Fechar</button></div><div style={{marginTop:11,display:'grid',gap:7}}>{(detalhe.campos||[]).filter(c=>Object.prototype.hasOwnProperty.call(detalhe.respostas||{},c.key)).map(c=><div key={c.key} style={{display:'grid',gridTemplateColumns:'minmax(180px,0.7fr) minmax(220px,1.3fr)',gap:10,padding:'8px 9px',borderRadius:7,background:theme.card,border:`1px solid ${theme.border}`}}><div style={{fontSize:10.5,fontWeight:850,color:theme.textSecondary}}>{c.label}</div><div style={{fontSize:11.5,fontWeight:850,color:theme.text}}>{valor(detalhe.respostas?.[c.key])}</div></div>)}</div><div style={{marginTop:12,padding:10,borderRadius:8,background:`${theme.warning}0F`,border:`1px solid ${theme.warning}55`,color:theme.textSecondary,fontSize:11.5,lineHeight:1.5}}>Ao confirmar, esses valores serão incorporados ao <strong>Banco Mestre Censo Docentes 2026</strong>. Depois disso, clique normalmente em <strong>Preparar formulário</strong> no professor para a conferência final antes do envio oficial.</div><button style={{...btn('success'),marginTop:10}} disabled={conferindo} onClick={()=>void confirmar()}>{conferindo?'Confirmando...':'✅ Conferi — incorporar ao Banco Mestre'}</button></div>}
  </section>;
}
